#!/usr/bin/env bash
#
# install_happymod_apk_docs.sh
#
# Discover HappyMod-related APKs under \$HOME, write a SHA-256 manifest, and
# regenerate evidence/raw/apk/README.md. Idempotent: manifest and README are
# recreated on every run to reflect current state.
#
# Usage:
#   ./install_happymod_apk_docs.sh

set -euo pipefail

say() { printf '%s\n' "$*" >&2; }

REPO_ROOT="$(git rev-parse --show-toplevel 2>/dev/null || true)"
if [[ -z "$REPO_ROOT" ]]; then
  say "ERROR: Must be run from inside the forensics-review repository."
  exit 1
fi
cd "$REPO_ROOT"

RAW_APK_DIR="$REPO_ROOT/evidence/raw/apk"
mkdir -p "$RAW_APK_DIR"

say "=== Repo root ==="
say "  $REPO_ROOT"
say

say "=== Scanning for HappyMod APKs under \$HOME (maxdepth 8) ==="
mapfile -t apks < <(
  find "$HOME" -maxdepth 8 \
    \( -iname 'happymod.apk' -o -iname 'happymod*.apk' \) \
    2>/dev/null | sort
)

if (( ${#apks[@]} > 0 )); then
  say "Found ${#apks[@]} APK candidate(s):"
  printf '  %s\n' "${apks[@]}" >&2
else
  say "WARNING: No happymod*.apk found under \$HOME."
fi
say

MANIFEST="$RAW_APK_DIR/happymod_apks.sha256"
# Always create/overwrite manifest, even if no APKs
: > "$MANIFEST"

if (( ${#apks[@]} > 0 )); then
  say "=== Writing manifest ==="
  say "  $MANIFEST"
  say
  for p in "${apks[@]}"; do
    if [[ -f "$p" ]]; then
      sha256sum "$p" >> "$MANIFEST"
    else
      say "NOTE: Skipping non-regular path: $p"
    fi
  done
else
  say "Manifest will be empty (no APKs discovered)."
fi

if [[ -s "$MANIFEST" ]]; then
  MANIFEST_SHA="$(sha256sum "$MANIFEST" | cut -d' ' -f1)"
else
  MANIFEST_SHA="(empty)"
fi

README_PATH="$RAW_APK_DIR/README.md"

cat > "$README_PATH" << RMD
# HappyMod APK Evidence (Raw)

This directory documents Android package (APK) files related to the HappyMod
application that are present on the capture/analysis device. The APK binaries
themselves are **not** tracked in Git; only this README and the hash manifest
are version-controlled.

## Hash Manifest

The file \`happymod_apks.sha256\` in this directory contains one line per APK,
in the standard \`sha256sum\` format:

\`\`\`text
<sha256>  <absolute_path_to_apk>
\`\`\`

This manifest is generated by running, from the repository root:

\`\`\`bash
cd "$REPO_ROOT" && ./install_happymod_apk_docs.sh
\`\`\`

Current manifest metadata:

- Path: \`evidence/raw/apk/happymod_apks.sha256\`
- SHA-256 of manifest contents: \`$MANIFEST_SHA\`

If any APK paths become invalid in the future (e.g., files are moved or deleted),
the recorded hashes still describe the original files.

## Discovery Procedure

APKs are discovered via:

\`\`\`bash
find "\$HOME" -maxdepth 8 \\
  \( -iname 'happymod.apk' -o -iname 'happymod*.apk' \) \\
  2>/dev/null | sort
\`\`\`

This includes typical variants such as:

- \`happymod.apk\`
- \`happymod_base.apk\`
- \`happymod_base__<suffix>.apk\`

Re-running \`install_happymod_apk_docs.sh\` will rescan the filesystem and
regenerate both the manifest and this README to reflect current state.

## Scope

This directory is **non-interpretive**. It only records that certain APK
artifacts existed at particular filesystem paths with particular SHA-256 hashes
at the time of generation. It does **not** assert intent, behavior, or any
legal or policy conclusion about those artifacts.
RMD

say "=== Documentation written ==="
say "  README:    $README_PATH"
say "  MANIFEST:  $MANIFEST"
say "  MANIFEST_SHA: $MANIFEST_SHA"
